/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.sales.system;
/**
 *
 * @author USER
 */
public class Inventory extends javax.swing.JFrame {
String product_id_to_update = ""; 

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
        product_load();
        supplier_load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_p_name = new javax.swing.JTextField();
        txt_p_barcode = new javax.swing.JTextField();
        txt_p_qty = new javax.swing.JTextField();
        txt_p_price = new javax.swing.JTextField();
        com_p_supplier = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Inventory Management");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 350, 40));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Bar Code", "Price", "Quantity", "Supplier Id"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 520, 350));

        jButton4.setText("Main Dashboard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 40));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Product Name");

        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Quantity");

        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Bar Code");

        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Price");

        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Suppolier Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_p_name, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_p_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_p_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_p_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(com_p_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_p_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_p_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_p_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_p_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(com_p_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 350));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = txt_p_name.getText();
String barcode = txt_p_barcode.getText();
String price = txt_p_price.getText();
String qty = txt_p_qty.getText();
String sid = com_p_supplier.getSelectedItem().toString(); // Direct ID

if (name.isEmpty() || barcode.isEmpty() || price.isEmpty() || qty.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", 2);
    return;
}

try {
    java.sql.Connection con = pharmacy.sales.system.db.mycon();
    String sql = "INSERT INTO products (product_name, bar_code, price, qty, supplier_id) VALUES (?,?,?,?,?)";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    
    pst.setString(1, name);
    pst.setString(2, barcode);
    pst.setString(3, price);
    pst.setString(4, qty);
    pst.setString(5, sid);
    
    pst.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Product: " + name + " added successfully!");
    
    clearFields();
    product_load(); 
    
} catch (java.sql.SQLException e) {
    if (e.getErrorCode() == 1062) { 
        javax.swing.JOptionPane.showMessageDialog(this, "This Barcode already exists!");
    } else {
        e.printStackTrace();
    }
}        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       
        try {
        int r = jTable1.getSelectedRow();
        
        // 1. Get Product ID for update/delete
        product_id_to_update = jTable1.getValueAt(r, 0).toString();
        
        // 2. Load Text Fields
        txt_p_name.setText(jTable1.getValueAt(r, 1).toString());
        txt_p_barcode.setText(jTable1.getValueAt(r, 2).toString());
        txt_p_price.setText(jTable1.getValueAt(r, 3).toString());
        txt_p_qty.setText(jTable1.getValueAt(r, 4).toString());
        
        // 3. Load Supplier ID to ComboBox
        // We get the ID from Column 5
        String table_sid = jTable1.getValueAt(r, 5).toString(); 

        // Force the ComboBox to select this ID
        com_p_supplier.setSelectedItem(table_sid);
        
        // If setSelectedItem still fails, use this fallback:
        for (int i = 0; i < com_p_supplier.getItemCount(); i++) {
            if (com_p_supplier.getItemAt(i).toString().equals(table_sid)) {
                com_p_supplier.setSelectedIndex(i);
                break;
            }
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
String name = txt_p_name.getText();
String barcode = txt_p_barcode.getText();
String price = txt_p_price.getText();
String qty = txt_p_qty.getText();
String sid = com_p_supplier.getSelectedItem().toString();

if (product_id_to_update.equals("")) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select a product from the table!");
    return;
}

try {
    java.sql.Connection con = pharmacy.sales.system.db.mycon();
    String sql = "UPDATE products SET product_name=?, bar_code=?, price=?, qty=?, supplier_id=? WHERE product_id=?";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    
    pst.setString(1, name);
    pst.setString(2, barcode);
    pst.setString(3, price);
    pst.setString(4, qty);
    pst.setString(5, sid);
    pst.setString(6, product_id_to_update);
    
    pst.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Product updated!");
    
    clearFields();
    product_load(); 
    product_id_to_update = "";
    
} catch (Exception e) {
    e.printStackTrace();
}        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
if (product_id_to_update.equals("")) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select a product from the table!");
    return;
}

int opt = javax.swing.JOptionPane.showConfirmDialog(this, "Delete this product?", "Confirm", 0);
if (opt == 0) {
    try {
        java.sql.Connection con = pharmacy.sales.system.db.mycon();
        String sql = "DELETE FROM products WHERE product_id = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, product_id_to_update);
        pst.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Deleted!");
        clearFields();
        product_load();
        product_id_to_update = "";
    } catch (Exception e) {
        e.printStackTrace();
    }
}        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }
    
    

 public void product_load() {
    try {
        java.sql.Connection con = pharmacy.sales.system.db.mycon();
        // Select exactly what we need
        String sql = "SELECT product_id, product_name, bar_code, price, qty, supplier_id FROM products";
        
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        dt.setRowCount(0); 
        
        while (rs.next()) {
            java.util.Vector v = new java.util.Vector();
            v.add(rs.getString("product_id"));    // Col 0
            v.add(rs.getString("product_name"));  // Col 1
            v.add(rs.getString("bar_code"));      // Col 2
            v.add(rs.getString("price"));         // Col 3
            v.add(rs.getString("qty"));           // Col 4
            v.add(rs.getString("supplier_id"));   // Col 5 - This must be the ID
            
            dt.addRow(v);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
 
 private void clearFields()
 {
    txt_p_name.setText("");
txt_p_barcode.setText("");
txt_p_price.setText("");
txt_p_qty.setText("");

if (com_p_supplier.getItemCount() > 0) {
    com_p_supplier.setSelectedIndex(0);
}

txt_p_name.requestFocus();
 }
      
      
 
 public void supplier_load() {
    try {
        java.sql.Connection con = pharmacy.sales.system.db.mycon();
        java.sql.Statement s = con.createStatement();
        java.sql.ResultSet rs = s.executeQuery("SELECT supplier_id FROM suppliers");
        
        com_p_supplier.removeAllItems();
        
        while (rs.next()) {
            // Add only the ID
            com_p_supplier.addItem(rs.getString("supplier_id"));
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Supplier Load Error: " + e.getMessage());
    }
}
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> com_p_supplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_p_barcode;
    private javax.swing.JTextField txt_p_name;
    private javax.swing.JTextField txt_p_price;
    private javax.swing.JTextField txt_p_qty;
    // End of variables declaration//GEN-END:variables
}
